### ISSUE TITLE
404 Client error when importing issues

### ISSUE THREAD

**Issue by johanv** [oasiswork/redmine-gitlab-migrator#12]
I created an empty project in Gitlab, and imported milestones from redmine with migrate-rg roadmap. This worked. The check for issue import worked as well:

```
migrate-rg issues --redmine-key XXXX --gitlab-key T5rbAsy6snApZPFbt5-w https://our.redmine.com/projects/migratie-test-project http://localhost/root/testproject --check
INFO: Project users are: PoppeJa 
INFO: Required users presence... OK
INFO: Project has no pre-existing issue... OK
INFO: Would create issue "-RM-5586-MR-sub task test" and 0 notes.
INFO: Would create issue "-RM-5585-MR-related issue test 2" and 0 notes.
INFO: Would create issue "-RM-5584-MR-related issue test 1" and 0 notes.
INFO: Would create issue "-RM-5583-MR-Standaard issue test" and 1 notes.
```

But importing without `--check` failed:

```
root@localhost:/# migrate-rg issues --redmine-key XXXX --gitlab-key T5rbAsy6snApZPFbt5-w https://our.redmine.com/projects/migratie-test-project http://localhost/root/testproject        
INFO: Project users are: PoppeJa 
INFO: Required users presence... OK
INFO: Project has no pre-existing issue... OK
Traceback (most recent call last):
  File "/opt/gitlab/embedded/bin/migrate-rg", line 9, in <module>
    load_entry_point('redmine-gitlab-migrator==1.0.2', 'console_scripts', 'migrate-rg')()
  File "/opt/gitlab/embedded/lib/python3.4/site-packages/redmine_gitlab_migrator/commands.py", line 237, in main
    args.func(args)
  File "/opt/gitlab/embedded/lib/python3.4/site-packages/redmine_gitlab_migrator/commands.py", line 146, in perform_migrate_issues
    created = gitlab_project.create_issue(data, meta)
  File "/opt/gitlab/embedded/lib/python3.4/site-packages/redmine_gitlab_migrator/gitlab.py", line 71, in create_issue
    issues_url, data=data, headers={'SUDO': meta['sudo_user']})
  File "/opt/gitlab/embedded/lib/python3.4/site-packages/redmine_gitlab_migrator/__init__.py", line 40, in post
    return self._req(requests.post, *args, **kwargs)
  File "/opt/gitlab/embedded/lib/python3.4/site-packages/redmine_gitlab_migrator/__init__.py", line 31, in _req
    resp.raise_for_status()
  File "/opt/gitlab/embedded/lib/python3.4/site-packages/requests/models.py", line 884, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost/api/v3/projects/root%2Ftestproject/issues
```
I am using gitlab 8.13.6, and redmine-gitlab-migrator 1.0.2.

Any suggestions?

Thank you,
Johan

**Comment by johanv** [comment]
Ok, my bad. The users were not added to the project I was migrating to, which caused the import to crash.

**Comment by marxistvegan** [comment]
I am having a similar issue, and wondering if the roles were a significant part to your solution? In my case the redmine side has 3 coordinators and the gitlab has 3 masters and 1 owner so in theory one more though one is the admin account which is reflected in both

**Comment by thorstent** [comment]
I had the same problem and it turns out I forgot to add the users to the group. I added the user to the Repo, but not the group. The problem is that the migrator impersonates the user who created the original issue. If that user (when logging in on the web frontend) is not able to see the project then you get a 404.

**Comment by omarpiani** [comment]
Happened to me with an user marked as "external" in gitlab
