### ISSUE TITLE
403-error creating issues after recent update of gitlab (v. 8.14.4)

### ISSUE THREAD

**Issue by johanv** [oasiswork/redmine-gitlab-migrator#17]
Technically this is not a bug in the redmine-gitlab-migrator, but I will just document this here in case someone bumps into this problem.

This is what I got when trying to migrate issues:

```
INFO: Project users are: PoppeJa 
INFO: Required users presence... OK
INFO: Project has no pre-existing issue... OK
Traceback (most recent call last):
  File "/var/www/vhosts/websites.chiro.be/migration/bin/migrate-rg", line 9, in <module>
    load_entry_point('redmine-gitlab-migrator==1.0.2', 'console_scripts', 'migrate-rg')()
  File "/var/www/vhosts/websites.chiro.be/migration/lib/python/redmine_gitlab_migrator-1.0.2-py3.4.egg/redmine_gitlab_migrator/commands.py", line 239, in main
  File "/var/www/vhosts/websites.chiro.be/migration/lib/python/redmine_gitlab_migrator-1.0.2-py3.4.egg/redmine_gitlab_migrator/commands.py", line 146, in perform_migrate_issues
  File "/var/www/vhosts/websites.chiro.be/migration/lib/python/redmine_gitlab_migrator-1.0.2-py3.4.egg/redmine_gitlab_migrator/gitlab.py", line 71, in create_issue
  File "/var/www/vhosts/websites.chiro.be/migration/lib/python/redmine_gitlab_migrator-1.0.2-py3.4.egg/redmine_gitlab_migrator/__init__.py", line 40, in post
  File "/var/www/vhosts/websites.chiro.be/migration/lib/python/redmine_gitlab_migrator-1.0.2-py3.4.egg/redmine_gitlab_migrator/__init__.py", line 31, in _req
  File "/var/www/vhosts/websites.chiro.be/migration/lib/python/requests-2.12.3-py3.4.egg/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://gitlab.chiro.be/api/v3/projects/test%2Ftestmigratie/issues
```

This is caused by an issue in gitlab: https://gitlab.com/gitlab-org/gitlab-ce/issues/25481.

I guess this issue will soon be fixed, but in the mean time, you can work around it by applying the patch attached. Beware that if you apply this patch, all issues and comments will appear to be posted by the user corresponding to the gitlab-key you use for the migration.

[gitab-sudo-workaround.zip](https://github.com/oasiswork/redmine-gitlab-migrator/files/644057/gitab-sudo-workaround.zip)

This is far from ideal. But if you need to migrate and you are stuck on a version of gitlab with this issue, it might be useful.

**Comment by voko** [comment]
Hi there. Some new findings from my side

a) I tried with gtilab-ce 8.15.2, still not working. See  [updated #25482](https://gitlab.com/gitlab-org/gitlab-ce/issues/25482#note_20676791)
b) does the ```%F2``` in the url have any impact?

**Comment by voko** [comment]
For future finders who are a freshman like me: there are two kind of tokens!

Solution: use the private token via *Profile Settings => Account*.
(and not the one in Access Tokens)

**Comment by romanr** [comment]
I have same issue with current Gitlab and current script version from repo:

```
INFO: create issue "..... " failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/migrate-rg", line 11, in <module>
    load_entry_point('redmine-gitlab-migrator==1.0.3', 'console_scripts', 'migrate-rg')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/commands.py", line 396, in main
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/commands.py", line 278, in perform_migrate_issues
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/gitlab.py", line 155, in create_issue
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/__init__.py", line 46, in post
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redmine_gitlab_migrator-1.0.3-py3.6.egg/redmine_gitlab_migrator/__init__.py", line 37, in _req
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://gitlab.com/api/v3/projects/432321/issues
```

Milestones were created correctly with the same token parameter. but issues can not be created.

**Comment by crud42** [comment]
I currently get

_API V3 is no longer supported. Use API V4 instead._ 

looks like the migration does not work due to major api version change on the gitlab side
