### ISSUE TITLE
404 on users json with redmine API

### ISSUE THREAD

**Issue by herau** [oasiswork/redmine-gitlab-migrator#3]
Redmine 2.5.1.stable
Gitlab 8.6.4

```shell
$ migrate-rg issues --redmine-key 7c2526a96c8603b683c2ae00474e88e3d79db9ca --gitlab-key owH5yfdvXTQtS61PqQms \
→   http://xxx/redmine/projects/uwa3 \
→   http://xxx/gitlab/redmine-wap --check
Traceback (most recent call last):
  File "/usr/local/bin/migrate-rg", line 9, in <module>
    load_entry_point('redmine-gitlab-migrator==1.0.2', 'console_scripts', 'migrate-rg')()
  File "/usr/local/lib/python3.5/site-packages/redmine_gitlab_migrator-1.0.2-py3.5.egg/redmine_gitlab_migrator/commands.py", line 237, in main
  File "/usr/local/lib/python3.5/site-packages/redmine_gitlab_migrator-1.0.2-py3.5.egg/redmine_gitlab_migrator/commands.py", line 111, in perform_migrate_issues
  File "/usr/local/lib/python3.5/site-packages/redmine_gitlab_migrator-1.0.2-py3.5.egg/redmine_gitlab_migrator/redmine.py", line 121, in get_users_index
  File "/usr/local/lib/python3.5/site-packages/redmine_gitlab_migrator-1.0.2-py3.5.egg/redmine_gitlab_migrator/redmine.py", line 115, in get_participants
  File "/usr/local/lib/python3.5/site-packages/redmine_gitlab_migrator-1.0.2-py3.5.egg/redmine_gitlab_migrator/redmine.py", line 17, in get
  File "/usr/local/lib/python3.5/site-packages/redmine_gitlab_migrator-1.0.2-py3.5.egg/redmine_gitlab_migrator/__init__.py", line 37, in get
  File "/usr/local/lib/python3.5/site-packages/redmine_gitlab_migrator-1.0.2-py3.5.egg/redmine_gitlab_migrator/__init__.py", line 31, in _req
  File "/usr/local/lib/python3.5/site-packages/requests-2.10.0-py3.5.egg/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error:  for url: http://xxx/redmine/users/3.json
```

I don't understand why the script request a `3.json` file ?

**Comment by JocelynDelalande** [comment]
@herau I'd be happy to include a fix if you find

- why the bug ?
- how to fix (patch)

But it's too far from my current concerns for me to be able to investigate it by myself.

**Comment by johanv** [comment]
You should check whether the redmine key you provide has admin rights on your redmine server. I got this error message as well, but after providing an api key for an admin, it worked. (Not really, I got another error message ;-))
