### ISSUE TITLE
TypeError: list indices must be integers, not str

### ISSUE THREAD

**Issue by jayblanc** [oasiswork/redmine-gitlab-migrator#6]
Trying to migrate milestones or issues gives this error : 

```
INFO: Project users are: ***,***,****
INFO: Required users presence... OK
INFO: Project has no pre-existing issue... OK
Traceback (most recent call last):
  File "/usr/local/bin/migrate-rg", line 9, in <module>
    load_entry_point('redmine-gitlab-migrator==1.0.2', 'console_scripts', 'migrate-rg')()
  File "/usr/local/lib/python3.4/dist-packages/redmine_gitlab_migrator/commands.py", line 237, in main
    args.func(args)
  File "/usr/local/lib/python3.4/dist-packages/redmine_gitlab_migrator/commands.py", line 146, in perform_migrate_issues
    created = gitlab_project.create_issue(data, meta)
  File "/usr/local/lib/python3.4/dist-packages/redmine_gitlab_migrator/gitlab.py", line 73, in create_issue
    issue_url = '{}/{}'.format(issues_url, issue['id'])
TypeError: list indices must be integers, not str
```

Any idea of what cause this bug ? 

Redmine 2.3.3
Gitlab 8.9.4
Python 3.4

**Comment by jayblanc** [comment]
The bug is due to http access to gitlb instead of https... This makes fail the POST request without any warning (json is empty).
